//********************************************************************************
// PANTHERID:  Alex Estrugo - 5210961, Ernesto Rodriguez - 4138075
// CLASS: COP 2210 – [Spring 18]
// ASSIGNMENT # [4]
// DATE: [4/17/2018]
//
//PATHERID OF ORIGINAL CODER: [4138075]
//
// I hereby swear and affirm that this work is solely my own, and not the work 
// or the derivative of the work of someone else, except as outlined in the 
// assignment instructions.
//********************************************************************************
package assignment.pkg3;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Ernesto Rodriguez
 * @author Alex Estrugo
 */

public class Game extends javax.swing.JFrame implements KeyListener
{
    private Player controls = new Player();
    public static DefaultListModel<String> itemsInRoomList = new DefaultListModel<>();
    public static DefaultListModel<String> itemsInBackpack = new DefaultListModel<>();
    
    public void keyPressed(KeyEvent k)
    {
        if (k.getKeyCode() == KeyEvent.VK_UP)
        {
            controls.move_up();
        }
        else if (k.getKeyCode() == KeyEvent.VK_DOWN)
        {
            controls.move_down();
        }
        else if (k.getKeyCode() == KeyEvent.VK_RIGHT)
        {
            controls.move_right();
        }
        else if (k.getKeyCode() == KeyEvent.VK_LEFT)
        {
            controls.move_left();
        }
    }
    
    public void keyTyped(KeyEvent k)
    {
        
    }
    
    public void keyReleased(KeyEvent k)
    {
        
    }
  
    /**
     * Add text to the diary.
     * @param string the string you want to add to the diary
     *@author Alex Estrugo
     */
    public static void addToDiary(String string)
    {
        diaryText.append("\n" + string);
    }
    
    public Game()
    {
        initComponents();
        addKeyListener(this);
        tutorialDialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        endingDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        restart_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        endingTextEffect = new javax.swing.JTextArea();
        endingTextBag = new javax.swing.JTextField();
        tutorialDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        playerNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        startGame = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        elevatorDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        elevatorList = new javax.swing.JList<>();
        elevatorButton = new javax.swing.JButton();
        infoDialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        close_button = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        infoTextEffect = new javax.swing.JTextArea();
        infoTextBag = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        playerIndicator = new javax.swing.JLabel();
        buttonAddToBag = new javax.swing.JButton();
        backpackLabel = new javax.swing.JLabel();
        scrollitemRoomList = new javax.swing.JScrollPane();
        itemsGUI = new javax.swing.JList<>();
        itemListLabel = new javax.swing.JLabel();
        addButtonExplain = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        diaryText = new javax.swing.JTextArea();
        diaryLabel = new javax.swing.JLabel();
        scrollitemRoomList1 = new javax.swing.JScrollPane();
        backpack = new javax.swing.JList<>();
        checkItemButton = new javax.swing.JButton();
        addButtonExplain1 = new javax.swing.JLabel();

        endingDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        endingDialog.setTitle("Death by Spook");
        endingDialog.setBackground(new java.awt.Color(250, 250, 250));
        endingDialog.setResizable(false);
        endingDialog.addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                endingDialogWindowClosed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        restart_button.setText("Restart");
        restart_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                restart_buttonActionPerformed(evt);
            }
        });

        endingTextEffect.setEditable(false);
        endingTextEffect.setColumns(20);
        endingTextEffect.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        endingTextEffect.setLineWrap(true);
        endingTextEffect.setRows(5);
        endingTextEffect.setWrapStyleWord(true);
        endingTextEffect.setBorder(null);
        jScrollPane1.setViewportView(endingTextEffect);

        endingTextBag.setEditable(false);
        endingTextBag.setBackground(new java.awt.Color(255, 255, 255));
        endingTextBag.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        endingTextBag.setText("jTextField1");
        endingTextBag.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(restart_button))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(endingTextBag))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(endingTextBag, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(restart_button)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout endingDialogLayout = new javax.swing.GroupLayout(endingDialog.getContentPane());
        endingDialog.getContentPane().setLayout(endingDialogLayout);
        endingDialogLayout.setHorizontalGroup(
            endingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        endingDialogLayout.setVerticalGroup(
            endingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        endingDialog.pack();
        endingDialog.setLocationRelativeTo(null);

        tutorialDialog.setTitle("Tutorial");
        tutorialDialog.addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                tutorialDialogWindowClosing(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        playerNameField.setText("Skeleton");
        playerNameField.setSelectionStart(0);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to the Spooky Tower");

        jLabel2.setText("Enter your name below to get spooked.");

        jLabel3.setText("You will begin at the entrance of my very spooky tower.");

        jLabel4.setText("To move your character, use the arrow keys on your keyboard.");

        jLabel5.setText("The arrows on the map will correspond to what room your character will move to.");

        startGame.setText("Start Game");
        startGame.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                startGameActionPerformed(evt);
            }
        });

        jLabel6.setText("The diary on the bottom right will update throughout the game. Keep an eye out for it.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(startGame)
                            .addGap(264, 264, 264))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(123, 123, 123))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(93, 93, 93)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(startGame)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout tutorialDialogLayout = new javax.swing.GroupLayout(tutorialDialog.getContentPane());
        tutorialDialog.getContentPane().setLayout(tutorialDialogLayout);
        tutorialDialogLayout.setHorizontalGroup(
            tutorialDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tutorialDialogLayout.setVerticalGroup(
            tutorialDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tutorialDialog.pack();
        tutorialDialog.setLocationRelativeTo(null);

        elevatorDialog.setTitle("Elevator Control");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        DefaultListCellRenderer renderer = (DefaultListCellRenderer) elevatorList.getCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        elevatorList.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Floor 0", "Floor 1", "Floor 2", "Floor 3", "Floor 4", "Floor 5", "Floor 6", "Floor 7", "Floor 8", "Floor 9", "Floor 10", "Floor 11", "Floor 12" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(elevatorList);

        elevatorButton.setText("Go");
        elevatorButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                elevatorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(elevatorButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(elevatorButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout elevatorDialogLayout = new javax.swing.GroupLayout(elevatorDialog.getContentPane());
        elevatorDialog.getContentPane().setLayout(elevatorDialogLayout);
        elevatorDialogLayout.setHorizontalGroup(
            elevatorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, elevatorDialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        elevatorDialogLayout.setVerticalGroup(
            elevatorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        elevatorDialog.pack();
        elevatorDialog.setLocationRelativeTo(null);

        infoDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        infoDialog.setTitle("Information");
        infoDialog.setBackground(new java.awt.Color(250, 250, 250));
        infoDialog.setResizable(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        close_button.setText("Close");
        close_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                close_buttonActionPerformed(evt);
            }
        });

        infoTextEffect.setEditable(false);
        infoTextEffect.setColumns(20);
        infoTextEffect.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        infoTextEffect.setLineWrap(true);
        infoTextEffect.setRows(5);
        infoTextEffect.setWrapStyleWord(true);
        infoTextEffect.setBorder(null);
        jScrollPane4.setViewportView(infoTextEffect);

        infoTextBag.setEditable(false);
        infoTextBag.setBackground(new java.awt.Color(255, 255, 255));
        infoTextBag.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        infoTextBag.setText("jTextField1");
        infoTextBag.setBorder(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(close_button)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(infoTextBag, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(infoTextBag, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(close_button)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout infoDialogLayout = new javax.swing.GroupLayout(infoDialog.getContentPane());
        infoDialog.getContentPane().setLayout(infoDialogLayout);
        infoDialogLayout.setHorizontalGroup(
            infoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        infoDialogLayout.setVerticalGroup(
            infoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        infoDialog.pack();
        infoDialog.setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spooky Tower");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        playerIndicator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/pkg3/locations/Floor 1.png"))); // NOI18N
        playerIndicator.setToolTipText("");

        buttonAddToBag.setText("Add");
        buttonAddToBag.setFocusable(false);
        buttonAddToBag.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonAddToBagActionPerformed(evt);
            }
        });

        backpackLabel.setText("Backpack");

        itemsGUI.setModel(itemsInRoomList);
        itemsGUI.setToolTipText("");
        itemsGUI.setFocusable(false);
        scrollitemRoomList.setViewportView(itemsGUI);

        itemListLabel.setText("Items in the Room");

        addButtonExplain.setText("Select an item above to add to your bag");

        diaryText.setEditable(false);
        diaryText.setColumns(20);
        diaryText.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        diaryText.setLineWrap(true);
        diaryText.setRows(5);
        diaryText.setWrapStyleWord(true);
        diaryText.setFocusable(false);
        jScrollPane2.setViewportView(diaryText);

        diaryLabel.setText("Skeleton's Diary");

        backpack.setModel(itemsInBackpack);
        backpack.setToolTipText("");
        backpack.setFocusable(false);
        scrollitemRoomList1.setViewportView(backpack);

        checkItemButton.setText("Check Item");
        checkItemButton.setFocusable(false);
        checkItemButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkItemButtonActionPerformed(evt);
            }
        });

        addButtonExplain1.setText("Select an item above to investigate it.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(playerIndicator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(itemListLabel)
                                .addGap(102, 102, 102))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(backpackLabel)
                                        .addGap(73, 73, 73))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(scrollitemRoomList1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(5, 5, 5)
                                            .addComponent(addButtonExplain1)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(diaryLabel)
                                            .addComponent(checkItemButton))
                                        .addGap(50, 50, 50)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(scrollitemRoomList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(addButtonExplain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(50, 50, 50))))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonAddToBag, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(playerIndicator)
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(itemListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollitemRoomList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButtonExplain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAddToBag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backpackLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollitemRoomList1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(addButtonExplain1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkItemButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diaryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddToBagActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonAddToBagActionPerformed
    {//GEN-HEADEREND:event_buttonAddToBagActionPerformed
        if (itemsGUI.getSelectedValue() != null)
        {
            controls.add_items_to_bag();            
        }
    }//GEN-LAST:event_buttonAddToBagActionPerformed

    private void restart_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_restart_buttonActionPerformed
    {//GEN-HEADEREND:event_restart_buttonActionPerformed
        controls.execute_restart();
        endingDialog.dispose();
        diaryText.setText("Hello, my name is " + playerNameField.getText() + ". I shall be exploring this house in search of spookiness to squelch.");
    }//GEN-LAST:event_restart_buttonActionPerformed

    private void endingDialogWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_endingDialogWindowClosed
    {//GEN-HEADEREND:event_endingDialogWindowClosed
        controls.execute_restart();
    }//GEN-LAST:event_endingDialogWindowClosed

    private void startGameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_startGameActionPerformed
    {//GEN-HEADEREND:event_startGameActionPerformed
        if (playerNameField.getText() != null && !(playerNameField.getText().equals("")))
        {
            controls.setPlayerName(playerNameField.getText());
            diaryLabel.setText(playerNameField.getText() + "'s Diary");
            diaryText.setText("Hello, my name is " + playerNameField.getText() + ". I shall be exploring this house in search of spookiness to squelch.");
            this.setVisible(true);
            tutorialDialog.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Name cannot be empty.");
        }
    }//GEN-LAST:event_startGameActionPerformed

    private void tutorialDialogWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_tutorialDialogWindowClosing
    {//GEN-HEADEREND:event_tutorialDialogWindowClosing
        System.exit(0);
    }//GEN-LAST:event_tutorialDialogWindowClosing

    private void elevatorButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_elevatorButtonActionPerformed
    {//GEN-HEADEREND:event_elevatorButtonActionPerformed
        controls.elevatorControl(elevatorList.getSelectedValue());
        elevatorDialog.dispose();
    }//GEN-LAST:event_elevatorButtonActionPerformed

    /**
     * Will first generate an array of items deemend safe (won't trigger game restart). 
     * If the boolean safety stays false. Then the gameover dialog window (endingDialog) will show
     * If the item being checked is safe. The information window will show.
     * This serves as a way of opening chest and obtaining the keys from their perspective chest.
     *@author Ernesto Rodriguez
     */
    private void checkItemButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkItemButtonActionPerformed
    {//GEN-HEADEREND:event_checkItemButtonActionPerformed
        if (backpack.getSelectedValue() != null)
        {
            String[] safeItems = {  "Storageroom Chest", "Key #1", "Attic Chest", "Key #2", "Refrigerator", "Dusty recipe box", "Broom",
                                    "Mirror", "Shower", "Rocking chair", "Window", "Doll House", "Intricate Oil Lamp", "Candelabra"};
            boolean safety = false;
            int i = 0;
            while (i < safeItems.length)
            {
                if (backpack.getSelectedValue().equals(safeItems[i]))
                {
                    safety = true;
                    break;
                }
                else
                    safety = false;
                i++;
            }

            if (safety)
            {
                controls.explore_items(backpack.getSelectedValue(), infoTextBag, infoTextEffect);
                infoDialog.setVisible(true);
            }
            else
            {
                controls.explore_items(backpack.getSelectedValue(), endingTextBag, endingTextEffect);
                endingDialog.setVisible(true);  
            }
        }
    }//GEN-LAST:event_checkItemButtonActionPerformed

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_close_buttonActionPerformed
    {//GEN-HEADEREND:event_close_buttonActionPerformed
        infoDialog.dispose();
    }//GEN-LAST:event_close_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Game();                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addButtonExplain;
    private javax.swing.JLabel addButtonExplain1;
    public static javax.swing.JList<String> backpack;
    private javax.swing.JLabel backpackLabel;
    private javax.swing.JButton buttonAddToBag;
    private javax.swing.JButton checkItemButton;
    private javax.swing.JButton close_button;
    private javax.swing.JLabel diaryLabel;
    private static javax.swing.JTextArea diaryText;
    private javax.swing.JButton elevatorButton;
    public static javax.swing.JDialog elevatorDialog;
    private javax.swing.JList<String> elevatorList;
    public static javax.swing.JDialog endingDialog;
    public static javax.swing.JTextField endingTextBag;
    public static javax.swing.JTextArea endingTextEffect;
    private javax.swing.JDialog infoDialog;
    private javax.swing.JTextField infoTextBag;
    private javax.swing.JTextArea infoTextEffect;
    private javax.swing.JLabel itemListLabel;
    public static javax.swing.JList<String> itemsGUI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JLabel playerIndicator;
    private javax.swing.JTextField playerNameField;
    private javax.swing.JButton restart_button;
    private javax.swing.JScrollPane scrollitemRoomList;
    private javax.swing.JScrollPane scrollitemRoomList1;
    private javax.swing.JButton startGame;
    private javax.swing.JDialog tutorialDialog;
    // End of variables declaration//GEN-END:variables


}

